package puzzle_city_client_model;


public enum ApiEnum {
	CITY_CREATE,CITY_UPDATE,CITY_GET_ONE,DELETE,CITY_FIND_ALL,CLOSE_CONNECTION,
	SENSORAIR_CREATE,SENSORAIR_UPDATE,SENSORAIR_FIND_ONE,SENSORAIR_FIND_ALL,
	VEHICULESENSOR_CREATE, VEHICULESENSOR_UPDATE, VEHICULESENSOR_FIND_ONE, VEHICULESENSOR_FIND_ALL,

}
